### ISSUE TITLE
[Token Listing]: 

### ISSUE THREAD

**Issue by LHKgit** [Globiance/default-token-list#1]
### Token Name

USNOTA

### Token Symbol

USNOTA

### Token Address

xdcd04275e2fd2875beaade6a80b39a75d4fe267df6

### Token Decimals

6

### Has Fee On Transfer

Yes

### Token Logo link

https://yt3.ggpht.com/WS4jVLTJL7t_nciarQFIp8fwMUWU2vkoss0S2jIM6gpiIRSLwFI-RJc6yLrIci8bH8aFNMM6=s88-c-k-c0x00ffffff-no-rj

**Comment by LHKgit** [comment]
This was the only link I found fo the token logo. Please download it - thx!

**Comment by rudreshsolanki97** [comment]
yes, no worries.
Do note I have set the "Fee On Transfer" to false as I believe USNOTA does not have a TAX on its transfer unlike tokens like GBEX.

Closed with 7f245ee64d0459a2a5fcec010d2bae3e5df12c38
