### ISSUE TITLE
[Token Listing]: 

### ISSUE THREAD

**Issue by Fasbus** [Globiance/default-token-list#12]
### Token Name

BluePhoenix Investments Coin

### Token Symbol

BIC

### Token Address

 xdc93ff05a8a1b5cd7cb5bfe8a96220de56d836e6c0

### Token Decimals

12

### Has Fee On Transfer

No

### Token Logo link

https://drive.google.com/file/d/1eeJJ1BaRhkNiIJl1trI033o1sbbsCN2B/view

### Other Details

www.bluephoenix.investments

Die Firma entspringt einer klassischen Vermögensberatung und ist auch als solche angemeldet. Der CEO Gregor Langberg ist auch ShareHolder (Seedinvestor) bei www.blackmanta.capital, welche als BaFin reguliertes Unternehmen (Wertpapierdienstleistungsunternehmen) schon vor 3 Jahren die ersten STOs begleitet hat.

In Partnerschaft mit der Vermögensverwaltung www.vansterling.com haben wir alle Berechtigungen, Wertpapiere (STOs) zu vermitteln und können mit diesem Partner alle Prozesse mit dem Endkunden durchlaufen. (Beratung, Vermittlung, KYC, AML, Kundenbetreuung, AssetManagement)
Der Coin soll uns helfen unsere Community zu stärken. Der Endkunde kann mit dem Coin unsere Dienstleistungen zu einem günstigeren Tarif erhalten.

**Comment by rudreshsolanki97** [comment]
token listed in b06371dea35280ffc24fdcb0c4760471dc5be288
