### ISSUE TITLE
[Token Listing]: 

### ISSUE THREAD

**Issue by krishnayogik** [Globiance/default-token-list#2]
### Token Name

ECOIN

### Token Symbol

ECOIN

### Token Address

xdc536Dd70445cEA1E97F9bf1BadA04CbdA5199a2a1

### Token Decimals

10

### Has Fee On Transfer

No

### Token Logo link

https://imgur.com/a/BAnllGf.png

**Comment by rudreshsolanki97** [comment]
676d22b808e367ff2eb44643ab6c3825744937fc
