### ISSUE TITLE
[Token Listing]: 

### ISSUE THREAD

**Issue by xcantera** [Globiance/default-token-list#3]
### Token Name

Prime Numbers

### Token Symbol

PRNT

### Token Address

xdc0e11710aad67e7427cfbc12c353284c2e335f62c

### Token Decimals

18

### Has Fee On Transfer

No

### Token Logo link

https://github.com/PrimeNumbersNFT/media/blob/main/Logo%20V1%20Prime%20Numbers.jpg

**Comment by rudreshsolanki97** [comment]
Added in 0b7cddad7c4c839003a58b8bb1f059a9048a2e8d
