### ISSUE TITLE
[Token Listing]: DC

### ISSUE THREAD

**Issue by KazeONGUENE** [Globiance/default-token-list#5]
### Token Name

DATACHAIN

### Token Symbol

DC

### Token Address

xdc20b59e6c5deb7d7ced2ca823c6ca81dd3f7e9a3a

### Token Decimals

18

### Has Fee On Transfer

No

### Token Logo link

https://drive.google.com/file/d/1IgGgbmDv5CwFXIoLfEheQznoSSkcoxm_/view?usp=sharing

**Comment by KazeONGUENE** [comment]
Pairing:
dc_usdt
dc_usdg
dc_xdc
dc_eth
dc_btc

**Comment by rudreshsolanki97** [comment]
DC token has been added to the token list & is now live.
Please feel free to create a DC pool or add liquidity to existing DC pools.
