### ISSUE TITLE
[Token Listing]: 

### ISSUE THREAD

**Issue by XDCPOWER** [Globiance/default-token-list#6]
### Token Name

XDC POWER

### Token Symbol

POWER

### Token Address

xdcca7ef6a1b756db9444958f13c66ba163df6a910d

### Token Decimals

18

### Has Fee On Transfer

No

### Token Logo link

https://ibb.co/YtxLzNY

### Other Details

Hello github ,

For listing the XDC POWER :
I Allready added a pool on globiance DEX and added some liquidity to it --> 

https://dex.globiance.com/info/pool/xdc0c2aEA0D3371b70150938099ebE05F847369C3a5
(only the LOGO is still standard, therefore i hope it will be updated with this writing)
usefull links are: twitter : https://twitter.com/XDCPOWER
linktree: https://linktr.ee/XDCPOWER
Alot need to be added but it is a start

The goal is to connect entertainment , multimedia, music to the xdc network 
we are learning to achieve this, meanwhile the coin can already develop on the network

the total created coins are 10.000.000.000  , allready 5.000.000.000 added to the pool for people to trade them at this cheap price

with friendely Regards XDC POWER

If other info is needed ,please feel free to contact xdcpowercoin@hotmail.com

**Comment by rudreshsolanki97** [comment]
hello - token has been added to the token list. 
Commit: 1aa627c

**Comment by XDCPOWER** [comment]
We thank you

greetings Team POWER
________________________________
Van: RUDRESH SOLANKI ***@***.***>
Verzonden: zaterdag 21 mei 2022 8:26
Aan: Globiance/default-token-list ***@***.***>
CC: XDCPOWER ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Globiance/default-token-list] [Token Listing]: (Issue #6)


hello - token has been added to the token list.
Commit: 1aa627c<https://github.com/Globiance/default-token-list/commit/1aa627c46111232e992613053a83d947332d2c66>

**Comment by XDCPOWER** [comment]
Dear , I hereby inform you with deep regret that we are discontinuing the xdcpower , we had just started a few days but soon saw that we had some technical issues that made it impossible for us to continue with this, so before we do any further damage to the setup I hereby inform you that the project is stopped. Also because our team member does not want to continue with this,we had some disagreements ,I deeply regret to inform you, I thank you for your cooperation, I have already removed the coin from the pool list to get the LP swapped back , but it is probably still listed under tokens, we can't remove these ourselves unfortunately, we have already removed the token from our previous account. Greetings Jillo
________________________________
Van: RUDRESH SOLANKI ***@***.***>
Verzonden: zaterdag 21 mei 2022 8:26
Aan: Globiance/default-token-list ***@***.***>
CC: XDCPOWER ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Globiance/default-token-list] [Token Listing]: (Issue #6)


Closed #6<https://github.com/Globiance/default-token-list/issues/6> as completed.
